config-version: 2

name: 'edu_edfi_source'
version: '0.3.6'
require-dbt-version: [">=1.0.0", "<2.0.0"]

# This setting configures which "profile" dbt uses for this project.
profile: 'edu_edfi_source'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  edu_edfi_source:
    +copy_grants: true
    staging:
      +schema: stage
      edfi_3:
        base:
          +materialized: view
        intermediate:
          +materialized: ephemeral
          int_ef3__deduped_descriptors:
           +materialized: table
           +tags: ['bypass_rls']
        stage: 
          +materialized: table
      tpdm:
        +enabled: "{{ var('edu:tpdm:enabled', false) }}"
        base:
          +materialized: view
        stage:
          +materialized: table
          
vars:
  extensions: null
  
  # student discipline participation codes that map to non-offenders
  'edu:discipline:non_offender_codes': ['Victim', 'Witness', 'Reporter']
