config-version: 2

name: 'edu_edfi_source'
version: '0.4.10'
require-dbt-version: [">=1.0.0", "<2.0.0"]

# This setting configures which "profile" dbt uses for this project.
profile: 'edu_edfi_source'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  edu_edfi_source:
    +copy_grants: true
    staging:
      +schema: stage
      edfi_3:
        base:
          +materialized: view
        intermediate:
          +materialized: ephemeral
          int_ef3__deduped_descriptors:
           +materialized: table
           +tags: ['bypass_rls']
        stage: 
          +materialized: table
      tpdm:
        base:
          +materialized: view
        stage:
          +materialized: table
          
vars:
  extensions: null
  predefined_extensions:
    epdm:
      stg_ef3__credentials:
        tpdm_certification_route_descriptor:
          name: 'tpdm:certificationRouteDescriptor'
          dtype: 'varchar'
        tpdm_credential_status_descriptor:
          name: 'tpdm:credentialStatusDescriptor'
          dtype: 'varchar'
        tpdm_educator_role_descriptor:
          name: 'tpdm:educatorRoleDescriptor'
          dtype: 'varchar'
        tpdm_board_certification_indicator:
          name: 'tpdm:boardCertificationIndicator'
          dtype: 'boolean'
        tpdm_credential_certification_title:
          name: 'tpdm:certificationTitle'
          dtype: 'varchar'
        tpdm_credential_status_date:
          name: 'tpdm:credentialStatusDate'
          dtype: 'timestamp'
        tpdm_person_reference_person_id:
          name: 'tpdm:personReference:PersonId'
          dtype: 'varchar'
        tpdm_v_student_academic_records:
          name: 'tpdm:studentAcademicRecords'
          dtype: 'variant'
      stg_ef3__schools:
        tpdm_post_secondary_institution_reference_post_secondary_institution_id:
          name: 'tpdm:postSecondaryInstitutionReference:postSecondaryInstitutionId'
          dtype: 'int'
      stg_ef3__survey_responses:
        tpdm_person_reference_person_id:
          name: 'tpdm:personReference:PersonId'
          dtype: 'varchar'

  
  # student discipline participation codes that map to non-offenders
  'edu:discipline:non_offender_codes': ['Victim', 'Witness', 'Reporter']

  # epdm extension default disabled
  'src:predefined_extensions:epdm:enabled': False